// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3aHC3m8wU5A8NSeJYp6Hn2SRp4xu0jPo',
    appId: '1:550939487517:web:19b852acc83ecce5a7c5f4',
    messagingSenderId: '550939487517',
    projectId: 'ohmsim-c02b8',
    authDomain: 'ohmsim-c02b8.firebaseapp.com',
    storageBucket: 'ohmsim-c02b8.appspot.com',
    measurementId: 'G-B6YWJ6TZDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwwrQQTEE1jkVIGcyHGbXoStDok2qzqUA',
    appId: '1:550939487517:android:eccf11cedddff715a7c5f4',
    messagingSenderId: '550939487517',
    projectId: 'ohmsim-c02b8',
    storageBucket: 'ohmsim-c02b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SDIaUKGuIS-bAwAUlB0hNBipgAleckU',
    appId: '1:550939487517:ios:2a47583d0bf23e01a7c5f4',
    messagingSenderId: '550939487517',
    projectId: 'ohmsim-c02b8',
    storageBucket: 'ohmsim-c02b8.appspot.com',
    iosClientId:
        '550939487517-qdp637kt589u9lgjo35ul5iukilsm5b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohmsim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-SDIaUKGuIS-bAwAUlB0hNBipgAleckU',
    appId: '1:550939487517:ios:8b3e4986c1ad288aa7c5f4',
    messagingSenderId: '550939487517',
    projectId: 'ohmsim-c02b8',
    storageBucket: 'ohmsim-c02b8.appspot.com',
    iosClientId:
        '550939487517-jg7lituurap2d70ffo2c1nhq9j9df8o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohmsim.RunnerTests',
  );
}
